#
# This source file is part of the CS342 2023 Balance Team Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "5"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"
  end

  desc "Build and test"
  lane :test do
    run_tests(
      skip_build: true,
      derived_data_path: ".derivedData",
      code_coverage: true,
      devices: ["iPhone 15 Pro"],
      force_quit_simulator: true,
      reset_simulator: true,
      prelaunch_simulator: false,
      concurrent_workers: 1,
      max_concurrent_simulators: 1,
      result_bundle: true,
      output_directory: "."
    )
  end

  desc "Build app"
  lane :build do
    build_app(
      derived_data_path: ".derivedData",
      destination: "generic/platform=iOS",
      output_directory: ".build",
      archive_path: ".build/Balance.xcarchive",
    )
    # This is an unfortunate workaround for a bug in fastlane: https://github.com/fastlane/fastlane/pull/21319
    Dir.chdir("..") do
      sh(
        "
        xcodebuild \
          -exportArchive \
          -exportOptionsPlist ./fastlane/ExportOptions.plist \
          -archivePath ./.build/Balance.xcarchive \
          -exportPath ./.build
        "
      )
    end
  end

  desc "Sign in to the App Store Connect API"
  lane :signin do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
  end

  desc "Publish a beta release to internal TestFlight testers"
  lane :beta do
    signin
    increment_build_number(
      {
        build_number: latest_testflight_build_number + 1
      }
    )
    build
    commit = last_git_commit
    upload_to_testflight(
      ipa: "./.build/Balance.ipa",
      distribute_external: true,
      groups: [
        "CS342 2023"
      ],
      submit_beta_review: true,
      notify_external_testers: true,
      expire_previous_builds: true,
      changelog: commit[:message]
    )
  end
end
